trigger:
- master

pool:
  vmImage: 'Ubuntu-18.04'

variables:
  resourcegroup: 'surge-mlops'
  workspace: 'surge-price-ws'
  experiment: 'surge-price-mlops'
  aml_compute_target: 'amlcluster'
  model_name: 'surge-classifier'
  aks_name: 'aks-cluster01'
  aks_region: 'eastus'

steps:

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.6'
    architecture: 'x64'   


- task: Bash@3
  displayName: 'Install Requirements'
  inputs:
    targetType: filePath
    filePath: 'environment_setup/install_requirements.sh'
    workingDirectory: 'environment_setup'

- task: AzureCLI@1
  displayName: 'Install the CLI'
  inputs:
    azureSubscription: 'MLconnect'
    scriptLocation: inlineScript
    inlineScript: 'az extension add -n azure-cli-ml'

- task: AzureCLI@1
  displayName: 'Attach folder to workspace'
  inputs:
    azureSubscription: 'MLconnect'
    scriptLocation: inlineScript
    inlineScript: 'az ml folder attach -e $(experiment) -w $(workspace) -g $(resourcegroup) --path $(Build.SourcesDirectory)'

- task: AzureCLI@1
  displayName: 'Get or create AML Compute Target'
  inputs:
    azureSubscription: 'MLconnect'
    scriptLocation: inlineScript
    inlineScript: 'az ml run submit-script -d ./environment_setup/dependencies.yml 
    ./aml_service/create_aml_cluster.py --aml_compute_target $(aml_compute_target) 
    --path $(Build.SourcesDirectory)'

- task: AzureCLI@1
  displayName: 'Master Pipeline'
  inputs:
    azureSubscription: 'MLconnect'
    scriptLocation: inlineScript
    inlineScript: 'az ml run submit-script -d ./environment_setup/dependencies.yml 
    ./aml_service/pipelines_master.py --aml_compute_target $(aml_compute_target) 
    --model_name $(model_name) --aks_name $(aks_name) --aks_region $(aks_region) 
    --build_number $(Build.BuildNumber) --path $(Build.SourcesDirectory)'

- task: CopyFiles@2
  displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    Contents: '**'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: devops-for-ai'
  inputs:
    ArtifactName: 'devops-for-ai'
    publishLocation: 'container'
    pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
    TargetPath: '$(Build.ArtifactStagingDirectory)'
